version: "3.9"

services:
  tracker:
    build: .
    container_name: tracker
    command: python3 main.py
    env_file:
      - .env
    # command: tail -f /dev/null # Only use this if you want to start the container without the app
    volumes:
      - .:/code
